#!/usr/bin/env ruby

forge "https://forgeapi.puppetlabs.com"

mod 'stankevich-python', '1.9.0'

mod 'puppetlabs-apache', '1.8.1' # Some other module here requires puppetlabs-apache ~> 1.8.0

mod 'puppetlabs-stdlib'

# stahnma-epel is being manually included because stankevich-python 
# doesn't depend on stahnma-epel but should
# https://github.com/stankevich/puppet-python/issues/196
mod 'stahnma-epel'

# Uncomment credstash if you're using it
# mod 'gene1wood-credstash'

mod 'gene1wood-flaskoktaapp', :path => '/opt/src/puppet/modules/flaskoktaapp'